
import { Agent, AgentCategory, User, CommunityPost, Integration, Lead } from './types';

// --- Users & Builders ---

const mockBuilder: User = {
  id: 'b1',
  name: 'Sarah Chen',
  avatar: 'https://picsum.photos/id/64/100/100',
  role: 'builder',
  verified: true,
  email: 'sarah.chen@example.com',
  phone: '+1 (555) 123-4567',
  preferences: { currency: 'USD', notifications: { email: true, community: true } },
  portfolio: { downloads: ['2', '4'], uploads: ['1', '3', '5'], wishlist: ['6'] },
  type: 'independent_creator',
  bio: 'Ex-Salesforce engineer turned indie maker. I build robust automation tools for sales teams and CRMs.',
  expertise: ['Salesforce', 'Gmail API', 'Slack', 'Python'],
  stats: { totalAgents: 5, totalDownloads: 12500, avgRating: 4.8, avgTrust: 92, responseRate: '4h' },
  persona: 'Creator',
  contributionScore: 1540,
  activePoints: 890,
  joinedDate: 'Jan 2023',
  twoFactorEnabled: true,
  interests: ['Automation', 'SaaS', 'Python'],
  location: 'San Francisco, CA'
};

const mockBuilder2: User = {
  id: 'b2',
  name: 'DevDynamics',
  avatar: 'https://picsum.photos/id/65/100/100',
  role: 'builder',
  verified: false,
  email: 'team@devdynamics.io',
  preferences: { currency: 'USD', notifications: { email: true, community: false } },
  portfolio: { downloads: [], uploads: ['2', '4', '6'], wishlist: [] },
  type: 'startup',
  bio: 'A collective of senior DevOps engineers building tools to automate your infrastructure and code quality.',
  expertise: ['AWS', 'GitHub Actions', 'Terraform', 'Docker'],
  stats: { totalAgents: 8, totalDownloads: 45000, avgRating: 4.7, avgTrust: 89, responseRate: '12h' },
  persona: 'Creator',
  contributionScore: 2100,
  activePoints: 1200,
  joinedDate: 'Mar 2023',
  twoFactorEnabled: true,
  interests: ['DevOps', 'Cloud', 'Infrastructure'],
  location: 'New York, NY'
};

const mockEnterprise: User = {
  id: 'b3',
  name: 'Enterprise Automations',
  avatar: 'https://ui-avatars.com/api/?name=Enterprise+Automations&background=0D8ABC&color=fff',
  role: 'builder',
  verified: true,
  email: 'contact@ent-auto.com',
  preferences: { currency: 'USD', notifications: { email: true, community: true } },
  portfolio: { downloads: [], uploads: [], wishlist: [] },
  type: 'enterprise_partner',
  bio: 'Official partner for major ERP and Finance platforms. We deliver certified, secure, and compliant agents.',
  expertise: ['SAP', 'Oracle', 'QuickBooks', 'Workday'],
  stats: { totalAgents: 12, totalDownloads: 8500, avgRating: 4.9, avgTrust: 98, responseRate: '1h' },
  persona: 'Enterprise',
  contributionScore: 500,
  activePoints: 300,
  joinedDate: 'Jun 2023',
  twoFactorEnabled: true,
  interests: ['ERP', 'Finance', 'Compliance'],
  location: 'London, UK'
};

const mockUser: User = {
  id: 'u3',
  name: 'Jason Bourne',
  avatar: 'https://picsum.photos/id/100/100/100',
  role: 'buyer',
  email: 'jason@treadstone.com',
  phone: '+1 (555) 999-8888',
  preferences: { currency: 'EUR', notifications: { email: false, community: true } },
  portfolio: { downloads: ['1', '5'], uploads: [], wishlist: ['2', '3'] },
  persona: 'Professional',
  bio: 'Operations manager looking for efficiency tools.',
  contributionScore: 120,
  activePoints: 50,
  joinedDate: 'Oct 2023',
  interests: ['Productivity', 'Operations'],
  location: 'Berlin, DE'
};

export const MOCK_BUILDERS = [mockBuilder, mockBuilder2, mockEnterprise];

export const MOCK_LEADS: Lead[] = [
    { id: 'l1', name: 'Alice Walker', phone: '+1 555-0101', email: 'alice@startups.inc', organization: 'Startups Inc', agentName: 'Salesforce Lead Prioritizer', status: 'New', date: '2024-03-20' },
    { id: 'l2', name: 'David Kim', phone: '+1 555-0102', organization: 'FinTech Corp', agentName: 'Invoice Approver AI', status: 'Contacted', date: '2024-03-19' },
    { id: 'l3', name: 'Elena Rodriguez', phone: '+1 555-0103', email: 'elena@lawfirm.com', agentName: 'Legal Contract Reviewer', status: 'Qualified', date: '2024-03-18' },
];

export const MOCK_INTEGRATIONS: Integration[] = [
  { id: 'i1', name: 'Slack', icon: 'slack' },
  { id: 'i2', name: 'Gmail', icon: 'mail' },
  { id: 'i3', name: 'HubSpot', icon: 'database' },
  { id: 'i4', name: 'GitHub', icon: 'github' },
  { id: 'i5', name: 'Notion', icon: 'file-text' },
  { id: 'i6', name: 'Salesforce', icon: 'cloud' },
];

const getTrust = (score: number) => ({
  codeQuality: Math.min(100, score + 2),
  stability: Math.min(100, score - 1),
  community: Math.min(100, score + 1),
  updates: Math.min(100, score - 3),
  documentation: Math.min(100, score + 3),
  security: Math.min(100, score + 5),
  adoption: Math.min(100, score - 2)
});

// --- AGENTS ---
const TRENDING_AGENTS: Agent[] = [
  {
    id: 't-1',
    name: 'Salesforce Lead Prioritizer',
    tagline: 'Automatically score and route leads based on email intent.',
    description: 'Connects Salesforce and Gmail to analyze incoming lead emails using NLP. It scores leads based on budget, authority, need, and timing (BANT) and updates Salesforce custom fields automatically.',
    category: AgentCategory.Sales,
    price: 4999,
    pricingModel: 'monthly',
    rating: 4.9,
    reviewCount: 342,
    builder: mockBuilder,
    verified: true,
    systemLogos: ['Salesforce', 'Gmail', 'Slack'],
    trustScore: 95,
    trustBreakdown: getTrust(95),
    versions: [{ version: '2.4.0', date: '2024-03-10', changes: 'DeepSeek R1 integration', downloadUrl: '#' }],
    lastUpdate: '2024-03-10',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968914.png',
    isTopSeller: true,
    useCases: ['Automate lead prioritization in Salesforce', 'Reduce response time for high-value leads', 'Sync email intent with CRM fields'],
    features: ['BANT Analysis', 'Auto-Routing'],
    installs: 12500,
    integrations: [],
    reviews: [
      { id: 'r1', userId: 'u101', userName: 'Alice Morgan', userAvatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d', rating: 5, comment: 'Saved our SDRs about 10 hours a week.', date: '2 days ago', sentiment: 'positive' },
      { id: 'r2', userId: 'u102', userName: 'Bob Smith', userAvatar: 'https://i.pravatar.cc/150?u=a042581f4e29026704d', rating: 4, comment: 'Great tool, but setup took a bit longer than expected.', date: '1 week ago', sentiment: 'neutral' }
    ],
    checksum: 'a3f9d2...8e1',
    fileSize: '4.2 MB',
    purchaseEnabled: true,
    demoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    personas: ['Business Teams', 'Enterprise', 'Professionals'],
    b2cTags: ['Good for Sales'],
    badges: ['verified', 'top_seller', 'enterprise_ready', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 98,
    riskHistory: [],
    socialProof: ['Salesforce', 'Airbnb', 'Twilio'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 450000,
    views: 12000,
    conversionRate: 8.5,
    responseTimeHours: 4
  },
  {
    id: 't-2',
    name: 'HubSpot Campaign Optimizer',
    tagline: 'Real-time A/B testing adjustments for active workflows.',
    description: 'Monitors HubSpot marketing workflows 24/7. Automatically pauses underperforming branches and reallocates budget to high-converting emails and landing pages.',
    category: AgentCategory.Marketing,
    price: 2999,
    pricingModel: 'monthly',
    rating: 4.8,
    reviewCount: 215,
    builder: mockEnterprise,
    verified: true,
    systemLogos: ['HubSpot', 'Google Analytics'],
    trustScore: 92,
    trustBreakdown: getTrust(92),
    versions: [{ version: '1.8.2', date: '2024-03-08', changes: 'GA4 Event syncing', downloadUrl: '#' }],
    lastUpdate: '2024-03-08',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968872.png',
    isTopSeller: true,
    useCases: ['Workflow Optimization', 'Ad Spend Management', 'Real-time A/B Testing'],
    features: ['Real-time Adjustments', 'ROI Calculator'],
    installs: 8900,
    integrations: [],
    reviews: [],
    checksum: 'b7c1x4...9p2',
    fileSize: '8.1 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Enterprise'],
    b2cTags: [],
    badges: ['verified', 'enterprise_ready', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 95,
    riskHistory: [{ type: 'bug', version: '1.8.0', resolvedIn: '6h', date: '2024-02-15' }],
    socialProof: ['HubSpot', 'Zapier'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 280000,
    views: 8500,
    conversionRate: 6.2,
    responseTimeHours: 2
  },
  {
    id: 't-3',
    name: 'Slack Ticket Triage Agent',
    tagline: 'Turn Slack messages into categorized Jira/Zendesk tickets.',
    description: 'Listens to support channels, identifies bug reports vs feature requests, and automatically creates tickets in Jira or Zendesk with full context and thread summaries.',
    category: AgentCategory.CustomerSupport,
    price: 1500,
    pricingModel: 'monthly',
    rating: 4.7,
    reviewCount: 560,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['Slack', 'Jira', 'Zendesk'],
    trustScore: 89,
    trustBreakdown: getTrust(89),
    versions: [{ version: '3.1.0', date: '2024-03-12', changes: 'Added Linear support', downloadUrl: '#' }],
    lastUpdate: '2024-03-12',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/2111/2111615.png',
    isTopSeller: true,
    useCases: ['Support Triage', 'Bug Tracking', 'Reduce ticket triage time in Slack'],
    features: ['Sentiment Analysis', 'Duplicate Detection'],
    installs: 15400,
    integrations: [],
    reviews: [
       { id: 'r3', userId: 'u103', userName: 'Charlie Kim', userAvatar: 'https://i.pravatar.cc/150?u=a042581f4e29026024d', rating: 5, comment: 'Crucial for our dev team. The auto-labeling is spot on.', date: '3 days ago', sentiment: 'positive' }
    ],
    checksum: 'f4d2a1...3m9',
    fileSize: '2.5 MB',
    purchaseEnabled: true,
    demoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    personas: ['Business Teams', 'Professionals', 'Enterprise'],
    b2cTags: ['Good for Teams'],
    badges: ['top_seller', 'paid'],
    securitySignals: { signed: false, gated: true, docs: true, scanned: true },
    maintenanceScore: 88,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 120000,
    views: 18000,
    conversionRate: 3.5,
    responseTimeHours: 12
  },
  {
    id: 't-4',
    name: 'Notion Knowledge Curator',
    tagline: 'Keep your team wiki fresh and interconnected.',
    description: 'Scans your Notion workspace for outdated pages, broken links, and orphaned documents. Suggests internal links and tags to improve knowledge discovery.',
    category: AgentCategory.Productivity,
    price: 999,
    pricingModel: 'monthly',
    rating: 4.6,
    reviewCount: 180,
    builder: mockBuilder,
    verified: false,
    systemLogos: ['Notion', 'Slack'],
    trustScore: 85,
    trustBreakdown: getTrust(85),
    versions: [{ version: '1.5.0', date: '2024-02-28', changes: 'Archival logic update', downloadUrl: '#' }],
    lastUpdate: '2024-02-28',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/8856/8856951.png',
    useCases: ['Knowledge Management', 'Wiki Cleanup', 'Internal Link Building'],
    features: ['Auto-Tagging', 'Stale Content Alerts'],
    installs: 6200,
    integrations: [],
    reviews: [],
    checksum: 'g8h1j2...5k3',
    fileSize: '1.8 MB',
    purchaseEnabled: true,
    personas: ['Students', 'Professionals', 'Business Teams', 'Creators & Builders'],
    b2cTags: ['Good for Study', 'Good for Productivity'],
    badges: ['paid', 'featured'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 85,
    riskHistory: [],
    socialProof: ['Notion'],
    marketSegment: 'individuals',
    state: 'production',
    revenue: 45000,
    views: 9000,
    conversionRate: 5.1,
    responseTimeHours: 24
  },
  {
    id: 't-5',
    name: 'Python Code Refactorer',
    tagline: 'Automated PEP8 compliance and performance optimization.',
    description: 'Connects to GitHub repositories to review Pull Requests specifically for Python code. Suggests refactors for speed and readability, not just style.',
    category: AgentCategory.Development,
    price: 3500,
    pricingModel: 'monthly',
    rating: 4.9,
    reviewCount: 410,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['GitHub', 'GitLab'],
    trustScore: 94,
    trustBreakdown: getTrust(94),
    versions: [{ version: '2.0.1', date: '2024-03-01', changes: 'Pandas optimization rules', downloadUrl: '#' }],
    lastUpdate: '2024-03-01',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968350.png',
    useCases: ['Code Review', 'Tech Debt Reduction', 'Automated QA'],
    features: ['Complexity Scoring', 'Security Scan'],
    installs: 9100,
    integrations: [],
    reviews: [],
    checksum: 'k9l2m3...6n4',
    fileSize: '5.5 MB',
    purchaseEnabled: true,
    personas: ['Creators & Builders', 'Professionals', 'Enterprise'],
    b2cTags: [],
    badges: ['verified', 'enterprise_ready', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 92,
    riskHistory: [],
    socialProof: ['GitHub'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 310000,
    views: 11000,
    conversionRate: 7.2,
    responseTimeHours: 6
  },
  {
    id: 't-6',
    name: 'Invoice Approver AI',
    tagline: 'Match POs to invoices and draft approval emails.',
    description: 'Reads PDF invoices from email, matches them against QuickBooks/Xero Purchase Orders, and flags discrepancies. Auto-approves matches under $500.',
    category: AgentCategory.Finance,
    price: 5999,
    pricingModel: 'monthly',
    rating: 4.8,
    reviewCount: 120,
    builder: mockEnterprise,
    verified: true,
    systemLogos: ['QuickBooks', 'Xero', 'Gmail'],
    trustScore: 91,
    trustBreakdown: getTrust(91),
    versions: [{ version: '1.2.0', date: '2024-03-05', changes: 'Multi-currency support', downloadUrl: '#' }],
    lastUpdate: '2024-03-05',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/2855/2855198.png',
    useCases: ['AP Automation', 'Fraud Detection', 'Expedite Invoice Processing'],
    features: ['OCR Extraction', 'Approval Workflows'],
    installs: 4500,
    integrations: [],
    reviews: [],
    checksum: 'p2q3r4...7s5',
    fileSize: '12.4 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Enterprise'],
    b2cTags: [],
    badges: ['verified', 'enterprise_ready', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 90,
    riskHistory: [],
    socialProof: ['Intuit'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 250000,
    views: 5000,
    conversionRate: 4.8,
    responseTimeHours: 3
  },
  {
    id: 't-7',
    name: 'HR Onboarding Orchestrator',
    tagline: 'Provision accounts and schedule welcome meetings.',
    description: 'Triggers when a candidate is marked "Hired" in BambooHR. Creates Google Workspace accounts, invites to Slack channels, and schedules intro calls.',
    category: AgentCategory.HR,
    price: 2500,
    pricingModel: 'monthly',
    rating: 4.7,
    reviewCount: 95,
    builder: mockBuilder,
    verified: true,
    systemLogos: ['BambooHR', 'Google Workspace', 'Slack'],
    trustScore: 88,
    trustBreakdown: getTrust(88),
    versions: [{ version: '1.1.5', date: '2024-02-20', changes: 'Okta integration beta', downloadUrl: '#' }],
    lastUpdate: '2024-02-20',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/912/912318.png',
    useCases: ['Employee Onboarding', 'IT Provisioning', 'New Hire Setup'],
    features: ['Checklist Management', 'Account Creation'],
    installs: 3200,
    integrations: [],
    reviews: [],
    checksum: 't3u4v5...8w6',
    fileSize: '3.1 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Enterprise'],
    b2cTags: [],
    badges: ['paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 85,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 85000,
    views: 4000,
    conversionRate: 3.1,
    responseTimeHours: 18
  },
  {
    id: 't-8',
    name: 'Zoom Meeting Actioner',
    tagline: 'Transcribe, summarize, and assign Jira tasks.',
    description: 'Joins Zoom calls, identifies action items, and creates Jira tasks assigned to the mentioned owner. Emails summary to all attendees.',
    category: AgentCategory.Productivity,
    price: 1999,
    pricingModel: 'monthly',
    rating: 4.8,
    reviewCount: 800,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['Zoom', 'Jira', 'Gmail'],
    trustScore: 93,
    trustBreakdown: getTrust(93),
    versions: [{ version: '4.0.0', date: '2024-03-14', changes: 'Speaker diarization upgrade', downloadUrl: '#' }],
    lastUpdate: '2024-03-14',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/4401/4401470.png',
    isTopSeller: true,
    useCases: ['Meeting Minutes', 'Task Delegation', 'Summarize meeting notes in Google Workspace'],
    features: ['Voice Fingerprinting', 'CRM Sync'],
    installs: 18000,
    integrations: [],
    reviews: [],
    checksum: 'x4y5z6...9a1',
    fileSize: '6.7 MB',
    purchaseEnabled: true,
    personas: ['Professionals', 'Business Teams', 'Enterprise'],
    b2cTags: ['Good for Meetings'],
    badges: ['top_seller', 'verified', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 96,
    riskHistory: [],
    socialProof: ['Zoom', 'Atlassian'],
    marketSegment: 'individuals',
    state: 'production',
    revenue: 350000,
    views: 22000,
    conversionRate: 9.1,
    responseTimeHours: 8
  },
  {
    id: 't-9',
    name: 'SQL Query Generator',
    tagline: 'Text-to-SQL for non-technical PMs.',
    description: 'Connects to read-only Postgres/MySQL. Allows users to ask questions in Slack ("How many users signed up yesterday?") and returns the data + charts.',
    category: AgentCategory.Data,
    price: 3999,
    pricingModel: 'monthly',
    rating: 4.5,
    reviewCount: 310,
    builder: mockEnterprise,
    verified: true,
    systemLogos: ['PostgreSQL', 'Slack', 'Metabase'],
    trustScore: 87,
    trustBreakdown: getTrust(87),
    versions: [{ version: '1.4.0', date: '2024-03-02', changes: 'Schema hallucination fix', downloadUrl: '#' }],
    lastUpdate: '2024-03-02',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/2306/2306173.png',
    useCases: ['Business Intelligence', 'Self-serve Analytics', 'Data Democratization'],
    features: ['Query Explanation', 'Chart Rendering'],
    installs: 7500,
    integrations: [],
    reviews: [],
    checksum: 'b2c3d4...5e6',
    fileSize: '9.0 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Enterprise', 'Creators & Builders'],
    b2cTags: [],
    badges: ['enterprise_ready', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 89,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 190000,
    views: 6000,
    conversionRate: 4.2,
    responseTimeHours: 5
  },
  {
    id: 't-10',
    name: 'LinkedIn Content Scheduler',
    tagline: 'Draft, approve, and schedule posts from Notion.',
    description: 'Monitors a Notion database for post drafts. Uses LLMs to polish copy, generate hashtags, and schedules them via LinkedIn API once status is "Approved".',
    category: AgentCategory.Marketing,
    price: 1200,
    pricingModel: 'monthly',
    rating: 4.6,
    reviewCount: 450,
    builder: mockBuilder,
    verified: false,
    systemLogos: ['Notion', 'LinkedIn'],
    trustScore: 82,
    trustBreakdown: getTrust(82),
    versions: [{ version: '2.1.0', date: '2024-02-15', changes: 'Carousel support', downloadUrl: '#' }],
    lastUpdate: '2024-02-15',
    segment: 'trending',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/3536/3536505.png',
    useCases: ['Social Media Mgmt', 'Brand Voice', 'Automated Posting'],
    features: ['Hashtag Optimization', 'Image Alt Text'],
    installs: 5100,
    integrations: [],
    reviews: [],
    checksum: 'f6g7h8...9i0',
    fileSize: '1.5 MB',
    purchaseEnabled: true,
    personas: ['Professionals', 'Creators & Builders'],
    b2cTags: ['Good for Personal Brand'],
    badges: ['featured', 'paid'],
    securitySignals: { signed: false, gated: true, docs: true, scanned: true },
    maintenanceScore: 80,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'individuals',
    state: 'production',
    revenue: 25000,
    views: 15000,
    conversionRate: 2.8,
    responseTimeHours: 36
  }
];

const VIRAL_AGENTS: Agent[] = [
  {
    id: 'v-1',
    name: 'Competitor Price Watch',
    tagline: 'Scrape competitor sites and alert via Slack.',
    description: 'Monitors 5 competitor URLs daily. Detects price changes and posts alerts to a #pricing-alerts channel.',
    category: AgentCategory.Sales,
    price: 999,
    pricingModel: 'monthly',
    rating: 4.4,
    reviewCount: 88,
    builder: mockBuilder,
    verified: false,
    systemLogos: ['Slack', 'Google Sheets'],
    trustScore: 78,
    trustBreakdown: getTrust(78),
    versions: [{ version: '1.0.1', date: '2024-01-20', changes: 'Bug fixes', downloadUrl: '#' }],
    lastUpdate: '2024-01-20',
    segment: 'viral',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/854/854878.png',
    useCases: ['Market Research', 'Competitive Analysis'],
    features: ['Visual Diff', 'Historical Logging'],
    installs: 2100,
    integrations: [],
    reviews: [],
    checksum: 'j1k2l3...4m5',
    fileSize: '1.2 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Creators & Builders'],
    b2cTags: [],
    badges: ['paid'],
    securitySignals: { signed: false, gated: true, docs: false, scanned: true },
    maintenanceScore: 75,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'others',
    state: 'production',
    revenue: 12000,
    views: 4500,
    conversionRate: 1.5,
    responseTimeHours: 48
  },
  {
    id: 'v-2',
    name: 'Legal Contract Reviewer',
    tagline: 'Redline NDAs and MSAs automatically.',
    description: 'Upload a PDF contract; agent highlights risky clauses (indemnity, termination) and suggests standard fallback language.',
    category: AgentCategory.Operations,
    price: 8000,
    pricingModel: 'monthly',
    rating: 4.8,
    reviewCount: 150,
    builder: mockEnterprise,
    verified: true,
    systemLogos: ['DocuSign', 'Word'],
    trustScore: 94,
    trustBreakdown: getTrust(94),
    versions: [{ version: '2.2.0', date: '2024-03-01', changes: 'GDPR clause detection', downloadUrl: '#' }],
    lastUpdate: '2024-03-01',
    segment: 'viral',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/1570/1570998.png',
    useCases: ['Legal Ops', 'Compliance Review'],
    features: ['Risk Scoring', 'Clause Library'],
    installs: 3400,
    integrations: [],
    reviews: [],
    checksum: 'n6o7p8...9q0',
    fileSize: '15.5 MB',
    purchaseEnabled: true,
    personas: ['Enterprise', 'Business Teams'],
    b2cTags: [],
    badges: ['verified', 'enterprise_ready', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 98,
    riskHistory: [],
    socialProof: ['DocuSign'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 280000,
    views: 3200,
    conversionRate: 8.9,
    responseTimeHours: 2
  },
  {
    id: 'v-3',
    name: 'Figma to React Component',
    tagline: 'Generate Tailwind code from Figma nodes.',
    description: 'Select a frame in Figma, run the plugin, and get clean React + Tailwind code committed to a GitHub branch.',
    category: AgentCategory.Development,
    price: 2500,
    pricingModel: 'one-time',
    rating: 4.5,
    reviewCount: 320,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['Figma', 'GitHub', 'React'],
    trustScore: 88,
    trustBreakdown: getTrust(88),
    versions: [{ version: '3.0.0', date: '2024-02-10', changes: 'Flexbox logic overhaul', downloadUrl: '#' }],
    lastUpdate: '2024-02-10',
    segment: 'viral',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968705.png',
    useCases: ['Frontend Dev', 'Prototyping', 'Design Handoff'],
    features: ['Auto-Responsive', 'Variable Mapping'],
    installs: 8900,
    integrations: [],
    reviews: [],
    checksum: 'r1s2t3...4u5',
    fileSize: '3.8 MB',
    purchaseEnabled: true,
    personas: ['Creators & Builders', 'Students', 'Professionals'],
    b2cTags: ['Good for Study'],
    badges: ['paid', 'verified'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 85,
    riskHistory: [],
    socialProof: ['Figma'],
    marketSegment: 'individuals',
    state: 'production',
    revenue: 89000,
    views: 21000,
    conversionRate: 5.5,
    responseTimeHours: 16
  },
  {
    id: 'v-4',
    name: 'SEO Blog Writer 2.0',
    tagline: 'Research, Outline, and Write in Ghost/WordPress.',
    description: 'Takes a keyword, scrapes top 10 results, creates an outline, writes 2000 words, and uploads draft to CMS.',
    category: AgentCategory.Marketing,
    price: 4000,
    pricingModel: 'monthly',
    rating: 4.3,
    reviewCount: 500,
    builder: mockBuilder,
    verified: false,
    systemLogos: ['WordPress', 'Ghost', 'Google'],
    trustScore: 75,
    trustBreakdown: getTrust(75),
    versions: [{ version: '4.1.0', date: '2024-03-12', changes: 'Humanize text update', downloadUrl: '#' }],
    lastUpdate: '2024-03-12',
    segment: 'viral',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/2702/2702602.png',
    useCases: ['Content Marketing', 'SEO Optimization'],
    features: ['Keyword Density', 'Internal Linking'],
    installs: 12000,
    integrations: [],
    reviews: [],
    checksum: 'v6w7x8...9y0',
    fileSize: '4.9 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Professionals', 'Creators & Builders'],
    b2cTags: [],
    badges: ['paid'],
    securitySignals: { signed: false, gated: true, docs: true, scanned: true },
    maintenanceScore: 80,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'individuals',
    state: 'production',
    revenue: 60000,
    views: 18000,
    conversionRate: 3.2,
    responseTimeHours: 24
  },
  {
    id: 'v-5',
    name: 'AWS Cost Anomaly Detector',
    tagline: 'Alerts on EC2/S3 spending spikes.',
    description: 'Analyzes CloudWatch metrics and alerts via PagerDuty if predicted spend exceeds daily threshold by 20%.',
    category: AgentCategory.Operations,
    price: 1500,
    pricingModel: 'monthly',
    rating: 4.9,
    reviewCount: 60,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['AWS', 'PagerDuty', 'Slack'],
    trustScore: 96,
    trustBreakdown: getTrust(96),
    versions: [{ version: '1.0.5', date: '2024-01-15', changes: 'Lambda cost support', downloadUrl: '#' }],
    lastUpdate: '2024-01-15',
    segment: 'viral',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/873/873107.png',
    useCases: ['FinOps', 'DevOps', 'Cost Control'],
    features: ['Forecast', 'Root Cause Analysis'],
    installs: 1800,
    integrations: [],
    reviews: [],
    checksum: 'z1a2b3...4c5',
    fileSize: '2.2 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Enterprise'],
    b2cTags: [],
    badges: ['paid', 'verified', 'enterprise_ready'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 99,
    riskHistory: [],
    socialProof: ['AWS'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 45000,
    views: 2000,
    conversionRate: 9.8,
    responseTimeHours: 1
  },
  {
    id: 'v-6',
    name: 'Customer Churn Predictor',
    tagline: 'Analyze Intercom/Stripe data to flag at-risk accounts.',
    description: 'Combines support ticket sentiment with login frequency to score customer health. Pings CSMs in Slack when health drops.',
    category: AgentCategory.CustomerSupport,
    price: 6000,
    pricingModel: 'monthly',
    rating: 4.7,
    reviewCount: 90,
    builder: mockEnterprise,
    verified: true,
    systemLogos: ['Intercom', 'Stripe', 'Salesforce'],
    trustScore: 90,
    trustBreakdown: getTrust(90),
    versions: [{ version: '2.0.0', date: '2024-02-22', changes: 'New ML model', downloadUrl: '#' }],
    lastUpdate: '2024-02-22',
    segment: 'viral',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/4144/4144517.png',
    useCases: ['Customer Success', 'Churn Prevention'],
    features: ['Health Scoring', 'Playbook Triggers'],
    installs: 2500,
    integrations: [],
    reviews: [],
    checksum: 'd6e7f8...9g0',
    fileSize: '10.1 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Enterprise'],
    b2cTags: [],
    badges: ['paid', 'verified', 'enterprise_ready'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 92,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 180000,
    views: 4000,
    conversionRate: 5.2,
    responseTimeHours: 4
  }
];

const NEW_AGENTS: Agent[] = [
  {
    id: 'n-1',
    name: 'DeepSeek R1 Coder',
    tagline: 'Reasoning-heavy coding assistant for complex refactors.',
    description: 'Utilizes the DeepSeek R1 model to perform multi-file reasoning for architectural changes. Slower but more accurate than Copilot.',
    category: AgentCategory.Development,
    price: 2000,
    pricingModel: 'monthly',
    rating: 4.8,
    reviewCount: 15,
    builder: mockBuilder,
    verified: false,
    systemLogos: ['VS Code', 'GitHub'],
    trustScore: 70,
    trustBreakdown: getTrust(70),
    versions: [{ version: '0.9.0', date: '2024-03-15', changes: 'Initial Beta', downloadUrl: '#' }],
    lastUpdate: '2024-03-15',
    segment: 'new',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/1005/1005141.png',
    isNew: true,
    useCases: ['Complex Refactoring', 'Architecture Review'],
    features: ['Chain-of-Thought', 'Multi-file Edit'],
    installs: 450,
    integrations: [],
    reviews: [],
    checksum: 'h1i2j3...4k5',
    fileSize: '7.3 MB',
    purchaseEnabled: true,
    personas: ['Creators & Builders', 'Students', 'Professionals'],
    b2cTags: ['Good for Study'],
    badges: ['new', 'paid'],
    securitySignals: { signed: false, gated: true, docs: false, scanned: true },
    maintenanceScore: 80,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'individuals',
    state: 'production',
    revenue: 2000,
    views: 1200,
    conversionRate: 4.5,
    responseTimeHours: 12
  },
  {
    id: 'n-2',
    name: 'Linear Issue Drafter',
    tagline: 'Voice-to-Linear ticket creation.',
    description: 'Record a Loom or voice note, agent extracts steps to reproduce and creates a Linear issue with proper labels.',
    category: AgentCategory.Productivity,
    price: 500,
    pricingModel: 'one-time',
    rating: 4.2,
    reviewCount: 8,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['Linear', 'Loom'],
    trustScore: 85,
    trustBreakdown: getTrust(85),
    versions: [{ version: '1.0.0', date: '2024-03-14', changes: 'Launch', downloadUrl: '#' }],
    lastUpdate: '2024-03-14',
    segment: 'new',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/9542/9542847.png',
    isNew: true,
    useCases: ['Project Management', 'Bug Reporting'],
    features: ['Transcription', 'Auto-Labeling'],
    installs: 120,
    integrations: [],
    reviews: [],
    checksum: 'l6m7n8...9o0',
    fileSize: '1.1 MB',
    purchaseEnabled: true,
    personas: ['Business Teams', 'Creators & Builders'],
    b2cTags: [],
    badges: ['new', 'paid'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 100,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'individuals',
    state: 'draft',
    revenue: 60,
    views: 400,
    conversionRate: 2.1,
    responseTimeHours: 24
  },
  {
    id: 'n-3',
    name: 'Sora Video Prompt Tuner',
    tagline: 'Optimize prompts for OpenAI Sora.',
    description: 'Helps creative directors write detailed physics-compliant prompts for video generation models.',
    category: AgentCategory.Design,
    price: 1000,
    pricingModel: 'monthly',
    rating: 5.0,
    reviewCount: 5,
    builder: mockBuilder,
    verified: false,
    systemLogos: ['OpenAI', 'Discord'],
    trustScore: 65,
    trustBreakdown: getTrust(65),
    versions: [{ version: '0.1.0', date: '2024-03-16', changes: 'Alpha', downloadUrl: '#' }],
    lastUpdate: '2024-03-16',
    segment: 'new',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/3074/3074767.png',
    isNew: true,
    useCases: ['Video Production', 'Prompt Engineering'],
    features: ['Prompt Expansion'],
    installs: 80,
    integrations: [],
    reviews: [],
    checksum: 'p1q2r3...4s5',
    fileSize: '0.8 MB',
    purchaseEnabled: true,
    personas: ['Creators & Builders', 'Professionals'],
    b2cTags: [],
    badges: ['new', 'paid'],
    securitySignals: { signed: false, gated: true, docs: false, scanned: true },
    maintenanceScore: 70,
    riskHistory: [],
    socialProof: [],
    marketSegment: 'others',
    state: 'submission',
    revenue: 0,
    views: 150,
    conversionRate: 0,
    responseTimeHours: 48
  },
  {
    id: 'n-4',
    name: 'Supabase Row Security Auditor',
    tagline: 'Check RLS policies for leaks.',
    description: 'Scans your Supabase schema and RLS policies to identify tables that are accidentally public.',
    category: AgentCategory.Development,
    price: 0,
    pricingModel: 'one-time',
    rating: 4.5,
    reviewCount: 20,
    builder: mockBuilder2,
    verified: true,
    systemLogos: ['Supabase', 'PostgreSQL'],
    trustScore: 88,
    trustBreakdown: getTrust(88),
    versions: [{ version: '1.1.0', date: '2024-03-13', changes: 'Added policy simulation', downloadUrl: '#' }],
    lastUpdate: '2024-03-13',
    segment: 'new',
    imageUrl: '',
    logoUrl: 'https://cdn-icons-png.flaticon.com/512/2906/2906274.png',
    isNew: true,
    useCases: ['Security Audit', 'Database Admin'],
    features: ['RLS Simulation'],
    installs: 600,
    integrations: [],
    reviews: [],
    checksum: 't6u7v8...9w0',
    fileSize: '3.3 MB',
    purchaseEnabled: true,
    personas: ['Creators & Builders', 'Enterprise'],
    b2cTags: [],
    badges: ['new', 'free', 'verified'],
    securitySignals: { signed: true, gated: true, docs: true, scanned: true },
    maintenanceScore: 98,
    riskHistory: [],
    socialProof: ['Supabase'],
    marketSegment: 'enterprise',
    state: 'production',
    revenue: 0,
    views: 1200,
    conversionRate: 12.5,
    responseTimeHours: 24
  }
];

// --- MOCK COMMUNITY POSTS ---
export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 'p-1',
    threadId: 'th-1',
    title: 'Best practices for Sales Agent configuration?',
    content: 'I have been using the Salesforce Lead Prioritizer for a week. What are the best thresholds for BANT scoring to avoid false positives?',
    author: mockUser,
    likes: 24,
    views: 450,
    repliesCount: 12,
    replies: [
        { id: 'r1', author: mockBuilder, content: "We recommend starting with a score of 60 and tuning from there.", timestamp: '1 hour ago', isAcceptedAnswer: true },
        { id: 'r2', author: mockBuilder2, content: "Don't forget to map your custom fields first.", timestamp: '2 hours ago' }
    ],
    tags: ['Salesforce', 'Configuration', 'Best Practices'],
    category: 'Best Practices',
    status: 'answered',
    date: '2 hours ago',
    relatedAgentId: 't-1'
  },
  {
    id: 'p-2',
    threadId: 'th-2',
    title: 'Feature Request: HubSpot bidirectional sync',
    content: 'Currently the Campaign Optimizer only pushes updates. We need it to read deal stages from HubSpot to adjust ad spend better.',
    author: mockBuilder2,
    likes: 89,
    views: 1200,
    repliesCount: 5,
    replies: [],
    tags: ['HubSpot', 'Feature Request'],
    category: 'Feature Request',
    status: 'open',
    date: '1 day ago',
    relatedAgentId: 't-2'
  },
  {
    id: 'p-3',
    threadId: 'th-3',
    title: 'Bug: Zoom Meeting Actioner missing attendees',
    content: 'Since the last update, the agent sometimes fails to list all attendees in the summary email if they joined late.',
    author: mockUser,
    likes: 15,
    views: 89,
    repliesCount: 3,
    replies: [],
    tags: ['Bug', 'Zoom'],
    category: 'Bug',
    status: 'open',
    date: '3 days ago',
    relatedAgentId: 't-8'
  }
];

// --- COMBINED EXPORT ---
export const MOCK_AGENTS: Agent[] = [
  ...TRENDING_AGENTS,
  ...VIRAL_AGENTS,
  ...NEW_AGENTS
];

export const CATEGORIES = Object.values(AgentCategory);
